### ISSUE TITLE
Socket in chroot causes container import to fail

### ISSUE THREAD

**Issue by scarycall** [warewulf/warewulf#197] opened 2021-11-02 18:39 UTC
wwctl container import /chroot/CentOS-7.9-20211027T134954 centos7.9-hardened
[ERROR] 	  Could not import image: lchown /var/warewulf/chroots/centos7.9-hardened/rootfs/var/lib/gssproxy/default.sock: no such file or directory

What is in the directory referenced above in the chroot:
/chroot/CentOS-7.9-20211027T134954/var/lib/gssproxy
drwx------. 2 root root 6 Jun  9 16:10 clients/
srw-rw-rw-. 1 root root 0 Nov  2 09:08 default.sock=
drwx------. 2 root root 6 Jun  9 16:10 rcache/

deleting socket file from chroot allows image to be imported by wwctl.

**Comment by gmkurtzer** [comment] 2021-11-27 03:00
I think this is happening here: https://github.com/hpcng/warewulf/blob/main/internal/pkg/container/imprt.go#L71

from this package: github.com/containers/storage/drivers/copy

Which means, we may have to rewrite that to properly skip or deal with sockets.

**Comment by TerranWorks** [comment] 2022-02-19 21:47
I am having the same issue with an arch singularity container:
`` Could not import image: lchown /usr/local/var/warewulf/chroots/compute/rootfs/etc/pacman.d/gnupg/S.gpg-agent: no such file or directory ``

I also found that deleting the sockets allowed the container to be imported

**Comment by mslacken** [comment] 2023-02-01 07:19
Is there a way to reproduce this?

**Comment by anderbubble** [comment] 2023-09-13 18:29
@scarycall are you still having this issue? I haven't encountered this, but if it's still an issue can you suggest a way to reproduce it?

**Comment by anderbubble** [comment] 2024-09-27 19:08
Closing as duplicate of #892.

**Closed by anderbubble** 2024-09-27 19:08 UTC
Labels: bug, needs confirmation, container
